server:
  port: 8002
spring:
  application:
    name: passport  #这个名字是当前服务暴露早nacos注册中心的服务名
#配置nacos的服务器地址
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
#视图解析器
  mvc:
    view:
      prefix: /pages/
      suffix: .html
#设置负载均衡策略。
#user-service 为请求的微服务名称，即服务提供方的 spring.application.name 属性值
user-service:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
   #NFLoadBalancerRuleClassName: com.netflix.loadbalancer.策略类名
