server:
  port: 8001
spring:
  application:
    name: user-service  #这个名字是当前服务暴露早nacos注册中心的服务名
#配置nacos的服务器地址
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  profiles:
    active: mapper
